### ISSUE TITLE
Unable to see ES instance

### ISSUE THREAD

**Issue by DigiAngel** [cleesmith/pakquery#1]
Topic says it...I've modified the config a few times but pakquery can't seem to find my ES instance.  Is there some debug or log I can check?  Thank you.

**Comment by DigiAngel** [comment]
Exact error via browser:
~~~
ElasticSearch fatal error: no Elasticsearch node available
~~~

**Comment by cleesmith** [comment]
Please feel free to fork and enhance as I no longer actively work on this app or keep up with ES releases.
